// escrever titulo  console.log ('algoritmo que calcule e mostre a tabuada de um número digitado pelo usuário')
// criar variavel para o usuário escolher o numero a ser calculado
// escrever a operaçao n x 1 e calcular console.log ('n x 1 = '+(n*1))
// escrever a operaçao n x 2 e calcular console.log ('n x 2 = '+(n*2))
// escrever a operaçao n x 3 e calcular console.log ('n x 3 = '+(n*3))
// escrever a operaçao n x 4 e calcular console.log ('n x 4 = '+(n*4))
// escrever a operaçao n x 5 e calcular console.log ('n x 5 = '+(n*5))
// escrever a operaçao n x 6 e calcular console.log ('n x 6 = '+(n*6))
// escrever a operaçao n x 7 e calcular console.log ('n x 7 = '+(n*7))
// escrever a operaçao n x 8 e calcular console.log ('n x 8 = '+(n*8))
// escrever a operaçao n x 0 e calcular console.log ('n x 9 = '+(n*9))
// escrever a operaçao n x 10 e calcular console.log ('n x 10 = '+(n*10))

console.log ('TABUADA DO NUMERO '+n)
var readlineSync = require('readline-Sync');
var n = readlineSync.question ('qual a tabuada? ')
console.log (n +' x 1 = '+(n*1))
console.log (n +' x 2 = '+(n*2))
console.log (n +' x 3 = '+(n*3))
console.log (n +' x 4 = '+(n*4))
console.log (n +' x 5 = '+(n*5))
console.log (n +' x 6 = '+(n*6))
console.log (n +' x 7 = '+(n*7))
console.log (n +' x 8 = '+(n*8))
console.log (n +' x 9 = '+(n*9))
console.log (n +' x 10 = '+(n*10))